# Generated by Django 4.0 on 2023-09-10 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_public_id_alter_user_created_alter_user_updated'),
    ]

    operations = [
       
    ]
