# Generated by Django 4.0 on 2023-09-10 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0009_user_public_id'),
    ]

    operations = [
        
    ]
