# Generated by Django 4.0 on 2023-09-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0011_user_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator',
            new_name='avatar',
        ),
    ]
